"""Render output/evidence_table.md — the final evidence table/dashboard.

    python -m nyc_pipeline.evidence

Reads only published artifacts (metrics CSVs, validation report, retrieval report) so the
table can never drift from the numbers the pipeline actually produced.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "output"
REFERENCE = ROOT / "data/reference"

MONTHS = [f"2023-{m:02d}" for m in range(1, 13)]
LABELS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def label(month: str) -> str:
    return f"{LABELS[int(month[5:7]) - 1]} {month[:4]}"


def main() -> int:
    report = json.loads((OUT / "validation_report.json").read_text())
    wide = pd.read_csv(OUT / "metrics_monthly_wide.csv")
    hourly = pd.read_csv(OUT / "metrics_hourly_detail.csv")
    api = json.loads((REFERENCE / "api_retrieval_report.json").read_text())
    run_path = OUT / "run_manifest.json"
    run = json.loads(run_path.read_text()) if run_path.exists() else {}
    zone_detail_path = OUT / "metrics_zone_detail.csv"
    segments_path = OUT / "metrics_segments.csv"
    zone_detail = pd.read_csv(zone_detail_path) if zone_detail_path.exists() else None
    segments = pd.read_csv(segments_path) if segments_path.exists() else None

    gate = report["gate"]
    totals = report["totals"]
    latest_month = wide.sort_values("month").iloc[-1]["month"]
    latest = wide[wide.month == latest_month].iloc[0]
    worst_hours = (hourly[hourly["month"] == latest_month]
                   .sort_values("slow_share", ascending=False).head(3))
    trips = api["trips"][f"trips_2023:{api['trips'].get('year', 2023)}"] if False else None
    # retrieval block: the 2023 block is stored under the dataset:year key
    key = next((k for k in api.get("trips", {}) if k.endswith(":2023")), None)
    block = api.get("trips", {}).get(key, {}) if key else {}
    rt = block.get("totals", {})

    lines: list[str] = []
    a = lines.append
    a("# Evidence Table — NYC TLC Monthly Trip Metrics (2023)")
    a("")
    a(f"**Gate: {gate['status']}** · coverage {totals['coverage']*100:.2f}% "
      f"({totals['valid_rows']:,} valid / {totals['raw_rows']:,} raw rows, "
      f"{totals['quarantined_rows']:,} quarantined with reason codes)  ")
    a(f"Generated by `python -m nyc_pipeline.evidence` from published artifacts · "
      f"validation run `{report['generated_at'][:19]}Z` · "
      f"pipeline run `{run.get('run_id', 'n/a')}` (git {run.get('git_commit', 'n/a')})")
    if gate["reasons"]:
        a(f"**HOLD reasons:** {'; '.join(gate['reasons'])}")
    a("")

    a("## Metrics — the number leadership tracks is **M2** (12 months of 2023)")
    a("")
    a("| Month | Valid rate (M1) | **Reliability (M2)** | P50 (M3) | P90 (M3) | "
      "Invalid (M4) | Slow share (M5) | Trips |")
    a("|---|---:|---:|---:|---:|---:|---:|---:|")
    for m in wide.sort_values("month").itertuples():
        a(f"| {label(m.month)} | {m.valid_trip_rate:.2%} | **{m.trip_time_reliability:.2%}** | "
          f"{m.duration_p50_min:.1f} min | {m.duration_p90_min:.1f} min | "
          f"{m.invalid_trip_rate:.2%} | {m.slow_trip_share:.2%} | {int(m.valid_rows):,} |")
    a("")
    base = wide[wide.month == wide.sort_values("month").iloc[0]["month"]].iloc[0]
    a(f"**Reading:** M2 is judged against expected durations = P80 of **{base['month']}** per "
      f"distance-band × time-bucket (judgement call A4, **not** season-adjusted). The baseline "
      f"month scores ~80% by construction — a fairness check on the ruler. Month-to-month movement "
      f"mixes real change with seasonality (L4).")
    a("")

    a(f"## Where the KPI loses time — hours ({label(latest_month)})")
    a("")
    a("| Pickup hour | Trips | P50 | P90 | Slow share | Reliability |")
    a("|---:|---:|---:|---:|---:|---:|")
    for _, r in worst_hours.iterrows():
        a(f"| {int(r['hour']):02d}:00 | {int(r['trips']):,} | {r['duration_p50_min']:.1f} | "
          f"{r['duration_p90_min']:.1f} | {r['slow_share']:.1%} | {r['trip_time_reliability']:.1%} |")
    a("")
    a("![metrics overview](fig_metrics_overview.png)")
    a("")

    if zone_detail is not None:
        a(f"## Where the KPI loses time — zones ({label(latest_month)}, TLC zone ids)")
        a("")
        a("| Pickup zone | Borough | Trips | Reliability | Slow share | P90 |")
        a("|---|---|---:|---:|---:|---:|")
        zm = zone_detail[(zone_detail["month"] == latest_month) & zone_detail["rankable"]]
        for _, r in zm.nsmallest(5, "trip_time_reliability").iterrows():
            a(f"| {r['pickup_zone']} | {r['borough']} | {int(r['trips']):,} | "
              f"{r['trip_time_reliability']:.1%} | {r['slow_trip_share']:.1%} | "
              f"{r['duration_p90_min']:.1f} |")
        a("")
        if segments is not None:
            a("| Segment | Trips | Share | Reliability | P50 | Slow share |")
            a("|---|---:|---:|---:|---:|---:|")
            for _, r in segments[segments["month"] == latest_month].iterrows():
                a(f"| {r['segment']} | {int(r['trips']):,} | {r['share_of_trips']:.1%} | "
                  f"{r['trip_time_reliability']:.1%} | {r['duration_p50_min']:.1f} | "
                  f"{r['slow_trip_share']:.1%} |")
            a("")
        a("![zone map](fig_zone_map.png)")
        a("")

    a("## Retrieval evidence (API is the source of record)")
    a("")
    a(f"- Months retrieved: **{rt.get('months', 0)}/12** · rows stored **{rt.get('rows', 0):,}** · "
      f"reconciled against the API's own `COUNT(*)`: **{rt.get('months_reconciled', 0)}/12**")
    a(f"- Composite-key duplicates across the year: **{rt.get('composite_key_duplicates', 0)}** "
      f"(offset-paging integrity check)")
    a("- Raw API pages preserved under `data/api_raw/`; per-month parquet is hash-pinned in "
      "`data/manifest.json`")
    a("- Row conservation: raw == staged == quarantined + valid, asserted every run")
    a(f"- Rules: {sum(1 for r in report['rules'] if r['status'] == 'PASS')} PASS · "
      f"{sum(1 for r in report['rules'] if r['status'] == 'WARN')} WARN · "
      f"{sum(1 for r in report['rules'] if r['status'] == 'FAIL')} FAIL · "
      f"{sum(1 for r in report['rules'] if r['status'] == 'UNKNOWN')} UNKNOWN "
      f"(`output/validation_report.json`)")
    for r in [r for r in report["rules"] if r["status"] == "WARN"]:
        a(f"  - ⚠ {r['id']} {r['name']}: {r['fail_rate']:.2%} fail — {r['action']}")
    high = [r for r in report["rules"]
            if r["status"] == "PASS" and (r["fail_rate"] or 0) > 0.01]
    for r in high:
        a(f"  - ℹ {r['id']} {r['name']}: {r['fail_rate']:.2%} flagged (within tolerance) — "
          f"rows kept, see U5 in the K/U/A/L table")
    a("")

    a("## Known / Unknown / Assumption / Limitation")
    a("")
    a("| Type | ID | Statement | Owner / next step |")
    a("|---|---|---|---|")
    for x in report["assumptions"]:
        a(f"| Assumption | {x['id']} | {' '.join(x['text'].split())} | {x['owner']} |")
    for x in report["unknowns"]:
        a(f"| Unknown | {x['id']} | {' '.join(x['text'].split())} | {x.get('owner', '—')} |")
    for x in report["limitations"]:
        a(f"| Limitation | {x['id']} | {' '.join(x['text'].split())} | — |")
    a("| Known | K1 | Every month's row count equals the API's own COUNT(*) for the same window; "
      "raw pages, hashes and per-month provenance are preserved | — |")
    a("")

    a("## Decision this output supports")
    a("")
    a(f"**Publish** the 2023 monthly trip-performance report with the WARNs above disclosed "
      f"({len([r for r in report['rules'] if r['status'] == 'WARN'])} rules) and the open client "
      f"questions (U1-U5); **direct operations** to the worst hours and worst zones. "
      f"Do **not** publish causal claims (L3) or money metrics (L5).")
    a("")

    (OUT / "evidence_table.md").write_text("\n".join(lines))
    print(f"wrote {OUT / 'evidence_table.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
